version: "3"

services:
  db-mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - myapp-node-network

networks:
  myapp-node-network:
    driver: bridge
